<?php

namespace UserBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

public function getAllPosts($currentPage)
{
    $em = $this->getEntityManager();
    $query = $em->createQuery("select u from UserBundle\Entity\UserDetail u");
    $paginator = $this->paginate($query, $currentPage);

    return $paginator;
}

public function paginate($dql, $page, $limit = 5)
{
    $paginator = new Paginator($dql);

    $paginator->getQuery()->setFirstResult($limit * ($page - 1))->setMaxResults($limit); 
    return $paginator;
}

}
