<?php

namespace UserBundle\Repository;

/**
 * UserAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
