# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        UserBundle\Entity\Login:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: UserBundle:Login
                property: username
        # in_memory:
        #     memory: 
        #         users:
        #             admin:
        #                 password: admin
        #                 roles: "ROLE_ADMIN"
        #             saravana:
        #                 password: admin123
        #                 roles: "ROLE_USER"

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            provider: our_db_provider
            form_login:
                login_path:  login
                check_path: login
                default_target_path: list_user
                failure_path: login
                remember_me: false
                # always_use_default_target_path: true 

            logout:
                path: /user/logout
                target: /user
                invalidate_session: true
        # secured_area:
        #     pattern:    ^/
        #     anonymous: ~
        #     form_login:
        #         login_path:  login
        #         check_path:  login_check

    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: [ROLE_USER, ROLE_ADMIN ] }

    