UserBundle\Entity\AreaOfInterest:
    type: entity
    table: area_of_interest
    uniqueConstraints:
        interest_UNIQUE:
            columns:
                - interest
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        interest:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
