UserBundle\Entity\GraduationType:
    type: entity
    table: graduation_type
    uniqueConstraints:
        type_UNIQUE:
            columns:
                - type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
