UserBundle\Entity\UserGraduation:
    type: entity
    table: user_graduation
    indexes:
        fk_graduation_id_idx:
            columns:
                - graduation_id
        fk_user_graduation_Id_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        user:
            targetEntity: UserDetail
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: graduationType
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        graduation:
            targetEntity: GraduationType
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                graduation_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
