UserBundle\Entity\UserEmail:
    type: entity
    table: user_email
    indexes:
        fk_user_email_id_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        emailId:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: email_id
    manyToOne:
        user:
            targetEntity: UserDetail
            cascade: ["all"]
            fetch: LAZY
            mappedBy: null
            inversedBy: emailId
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
