UserBundle\Entity\UserDetail:
  properties:
    firstName:
      - NotBlank: {message: "Please provide your name"}
      - Length:
          min: 5
          max: 30
      - Regex:
          pattern: '/\d/'
          match: false
          message: Your Name cannot contain a number  
    lastName:
      - NotBlank: {message: "Please provide your name"}
      - Length:
          min: 5
          max: 30
      - Regex:
          pattern: '/\d/'
          match: false
          message: Your Name cannot contain a number
    dateOfBirth:
      - NotBlank: {message: "Please provide your date Of Birth"}
      - Date: ~
    gender:
      # - NotBlank: ~
      # - Choice: { callback: getGender }
    emailId:
      - valid: ~
    contactNumber:
      - valid: ~
    interest:
      - valid: ~
      # - NotBlank: {message: "Please select the field"}
      # - Choice: { callback: getInterest }
    bloodGroup:
      - NotBlank: {message: "Please select the field"}
      # - Choice: { callback: getBloodGroup }
    graduationType:
      - NotBlank: {message: "Please provide your graduation detail"}
    image:
      - Image:
        # allowLandscape: false
        # allowPortrait: false
          mimeTypesMessage: Please upload a Image
UserBundle\Entity\UserEmail:
  constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: emailId
  properties:
    emailId:
      - NotBlank: {message: "Please provide your Email Id"}
      - Email:
          message: The email "{{ value }}" is not a valid email.

UserBundle\Entity\UserContact:
  constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: contactNumber
  properties:
    contactNumber:
      - NotBlank: {message: "Please provide your contact number"}
      - Regex:
          pattern: '/\d+/'
          message: Please Provide valid number
      - Length:
          max: 13
# UserBundle\Entity\InterestType:
#   constraints:
#         - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: interest
#   properties:
#     interest:
#       - NotBlank: {message: "Please provide your Interest"}
UserBundle\Entity\UserGraduation:
  constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: graduation
  properties:
    graduation:
      - NotBlank: {message: "Please provide your graduation"}
# UserBundle\Entity\InterestType:
#   properties:
#     interest:
#       # - NotBlank: {message: "Please provide your contact number"}
#       - Choice: { callback: getInterest }




